### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by necov** [karaoak/TiAirPlay#1]
Hi! Great module - I've looked everywhere for a module to support in-app controls of airplay. However, my App crashes. When I navigate to the tab where my Radioplayer (audioplayer) is located, and start the player everything is fine, and I can control the airplay port. 

When I press the back button, my app crashes, and i get this error-log:

[DEBUG] [ioslib] [ios-sim] [DEBUG] Session did end with error (null)

[DEBUG] [ioslib] [ios-sim] [DEBUG] Removing named pipe at `/var/folders/nz/_0hly9994mld7gr19pk9d_k00000gn/T//ios-sim-stderr-pipe-1422352694'

[DEBUG] [ioslib] [ios-sim] [DEBUG] Removing named pipe at `/var/folders/nz/_0hly9994mld7gr19pk9d_k00000gn/T//ios-sim-stdout-pipe-1422352694'

[DEBUG] [ioslib] [ios-sim] Exited with code: 0

I've tried removing the module, and after that everything works fine. So I assume that it has something to do with your module.

Thansk!

**Comment by karaoak** [comment]
I don't use any tabs in my audio apps.
Can you send me code snippet of your tab setup? I will then hopefully be able to reproduce and fix.

rgrds, Frank
